# Generated by Django 5.2 on 2025-04-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovr_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('book', 'Book'), ('device', 'Device'), ('software', 'Software'), ('accessory', 'Accessory'), ('clothing', 'Clothing'), ('stationery', 'Stationery'), ('homegoods', 'HomeGoods')], max_length=10),
        ),
    ]
