# Generated by Django 5.2 on 2025-04-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovr_products', '0002_alter_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('book', 'Book'), ('device', 'Device'), ('software', 'Software'), ('accessory', 'Accessory')], max_length=20),
        ),
    ]
