# Generated by Django 5.2 on 2025-04-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovr_products', '0003_alter_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('book', 'Book'), ('device', 'Device'), ('accessory', 'Accessory'), ('clothing', 'Clothing')], max_length=20),
        ),
    ]
