# Generated by Django 5.2 on 2025-04-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovr_products', '0004_alter_category_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=55, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='products', to='ovr_products.genre'),
        ),
    ]
