# Generated by Django 5.2 on 2025-04-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovr_products', '0005_genre_product_genres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='BookGenre',
        ),
    ]
